import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_AE': {
          "appTitle": "برنامج مترو القاهرة",
          "line": "الخط",
          "currentStation": "المحطة اللي هتحرك منها",
          "openLocation": "افتح الموقع",
          "needLocationPermission": "محتاجين صلاحيات الموقع عشان نحدد أقرب محطة مترو ليك",
          "targetedStation": "المحطة اللي عاوز أروحها",
          "from": "من",
          "to": "إلى",
          "findRoute": "وريني أمشي ازاي",
          "addressHint": "العنوان اللي عاوز تروحه",
          "locationDeniedTitle": "ماينفعش تستخدم البرنامج دا",
          "map": "خريطة المترو",
          "locationDeniedMessage": "لازم تشغل اللوكيشن عشان نعرف مكانك ومنها نعرف أقرب محطة مترو",
          "locationDisabled": "اللوكيشن مقفول",
          "permanentlyDenied": "مش هنقدر نستخدم اللوكيشن عشان مقفول بشكل نهائي",
          "permissionsDisabled": "صلاحيات اللوكيشن مقفولة",
          "sameStations": "أنت بتعمل ايه؟!",
          "You're Already in": "أنت فعلًا موجود في محطة @station",
          "Station": "محطة",
          "exchangeStation": "هتحول @firstLineNumber @secondLineNumber عن طريق محطة @station",
          "expectedTime": "الوقت المتوقع:\n@timeد",
          "nearestStation": "ايه أقرب محطة ليا؟",
          "homePage": "الصفحة الرئيسيى",
          "history": "سجل الرحلات",
          "favorites": "رحلاتي المفضلة",
          "settings": "الإعدادات",
          "about": "عن البرنامج",
          "locationOfStation": "ازاي أروح للمحطة دي؟",
          "locationOfAddress": "ازاي أروح للعنوان دا؟",
          "nearestStationForAddress": "ايه أقرب محطة للعنوان دا؟",
          "noOfStations": "عدد المحطات:\n@stations @number",
          "Price": "سعر التذكرة للفرد:\n@price @currency"
        },
        'en_US': {
          "nearestStation": "Nearest Station",
          "locationOfStation": "Route to Station",
          "locationOfAddress": "Route to Address",
          "nearestStationForAddress": "Nearest Station",
          "appTitle": "Cairo Metro App",
          "homePage": "Home Page",
          "history": "History",
          "favorites": "Favorites",
          "settings": "Settings",
          "about": "About",
          "findRoute": "Find Route",
          "line": "Line",
          "currentStation": "Current Station",
          "openLocation": "Open Location",
          "needLocationPermission": "We need Location Permissions to find Nearest Station to you.",
          "map": "Metro Map",
          "targetedStation": "Targeted Station",
          "addressHint": "Address you Want to Go",
          "from": "from",
          "to": "to",
          "locationDeniedTitle": "You can't Use this App",
          "locationDeniedMessage":
              "You Should Open Location to determine your current location to find the nearest metro station",
          "locationDisabled": "The location service on the device is disabled.",
          "permanentlyDenied": "Location permissions are permanently denied, we cannot request permissions.",
          "permissionsDisabled": "Location permissions are denied",
          "sameStations": "What are you doing?!",
          "You're Already in": "You're Already in @station Station",
          "Station": "Station",
          "exchangeStation": "You will exchange @firstLineNumber to @secondLineNumber through @station Station",
          "expectedTime": "Expected Time:\n@timem",
          "noOfStations": "Number of Stations:\n@stations @number",
          "Price": "Price of each passenger:\n@price @currency"
        },
      };
}
